### ISSUE TITLE
SCD41 sensor returns temperature, humidity but shows CO2=0

### ISSUE THREAD

**Issue by kapyaar** [sparkfun/SparkFun_SCD4x_Arduino_Library#2]
Hi,

I bought both the sensor module by itself (Digikey# 1649-SCD41-D-R2CT-ND), as well as the dev kit for scd41 (digikey# 1649-SEK-SCD41-SENSOR-ND) from digikey. Running the basicReadings example, All works OK with the dev kit. Sample Serial output shows

`CO2(ppm):751.00	Temperature(C):20.5	Humidity(%RH):41.7`

but with the sensor module (Digikey# 1649-SCD41-D-R2CT-ND), CO2 reading is coming out as zero. 

`CO2(ppm):0	Temperature(C):21.1	Humidity(%RH):40.8`

I have two different modules, This is happening with both modules. Any Idea why?

**Comment by kapyaar** [comment]
Turns out the VDDH line needs to be powered. A continuity check was beeping between VDD and VDDH but an ohm test showed 8ohms, so definitely not a short. We ran power to both, and now it is working.

**Comment by nseidle** [comment]
Thanks for coming back to report the fix!
